DROP TABLE IF EXISTS music;

CREATE TABLE IF NOT EXISTS music(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    title TEXT NOT NULL,
    author TEXT NOT NULL,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TRIGGER [UpdateTime] AFTER UPDATE ON [music]
    BEGIN
        UPDATE music SET updated = CURRENT_TIMESTAMP WHERE id = OLD.id;
    END;